package:
  name: carculator_bus
  version: {{ environ['VERSION'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  script_env:
    - VERSION
    - CONDA_BLD_PATH

requirements:
  build:
    - python
    - setuptools
  run:
    - pandas
    - xarray
    - numpy
    - klausen
    - xlrd
    - numexpr
    - bw2io
    - prettytable
    - pycountry
    - atmos
    - wurst
    - pyyaml

test:
  imports:
    - carculator_bus

about:
  home: https://github.com/romainsacchi/carculator_bus
  license: BSD License
  summary: 'Life Cycle Assessment model for urban and coach buses.'
license_family: BSD